name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Make gradlew executable
      run: chmod +x ./app/gradlew  # Update the path if necessary

    - name: Build with Gradle
      run: ./app/gradlew build  # Update the path if necessary
