name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        android-version: [24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adoptopenjdk'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-version: ${{ matrix.android-version }}
          cache: true

      - name: Set up emulator
        run: |
          echo "y" | sdkmanager --licenses
          sdkmanager "system-images;android-24;google_apis;x86"
          avdmanager create avd --name test_device --package "system-images;android-24;google_apis;x86" --device "pixel" --force
          nohup emulator -avd test_device -no-window -noaudio -no-boot-anim &

      - name: Wait for emulator to start
        run: |
          adb wait-for-device
          adb shell input keyevent 82 &

      - name: Install dependencies
        run: |
          ./gradlew clean
          ./gradlew dependencies

      - name: Build the project
        run: ./gradlew testDebugUnitTest

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run Instrumented tests (Android tests)
        run: ./gradlew connectedDebugAndroidTest

      - name: List build output files
        run: |
          ls -R app/build/outputs

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results/testDebugUnitTest

      - name: Upload instrumented test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumented-test-results
          path: app/build/outputs/androidTest-results


